# Generated by Django 4.2.11 on 2024-06-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_event_meet_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=500, unique=True)),
                ('assignment_name', models.CharField(max_length=500)),
                ('assignment_description', models.CharField(max_length=500)),
                ('assignment_due_date', models.CharField(max_length=20)),
                ('assignment_submission_link', models.CharField(max_length=1000)),
            ],
        ),
    ]
