# Generated by Django 4.2.11 on 2024-06-09 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_submission_link',
            field=models.CharField(default='google.com', max_length=1000),
        ),
    ]
