# Generated by Django 4.2.11 on 2024-06-10 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_assignment_assignment_submission_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_submission_link',
            field=models.CharField(max_length=1000),
        ),
    ]
